package demo;
 
import com.demo.drools.server.User;

rule "Tests for Type 1 user"
salience 100
when
	user : User( code == 1 )
then	
	user.setType("Admin");
	user.setCountOfQuestions(10);
end

rule "Tests for Type 2 user"
salience 100
when
	user : User( code == 2 )
then	
	user.setType("Power");
	user.setCountOfQuestions(5);
end

rule "Tests for Type 3 user"
salience 100
when
	user : User( code == 3 )
then	
	user.setType("Basic");
	user.setCountOfQuestions(3);
end


